### ISSUE TITLE
IPOPT not detecting in Some Windows Platform (Python 3.7)

### ISSUE THREAD

**Issue by swaroopguggilam** [romcon/OPTALG#4]
OPTALG is unable to find ipopt or mumps even after successfull installation.
Verified that IPOPT and MUMPS library files are getting created and in appropriate location.
Even @fxz89 is having the same issue on her laptop as well.

Steps I followed:
1) Pip uninstall optalg
2) clean.bat (modified the code, it deletes the .c files as well)
3) python setup.py build_ext --inplace
4) nosetests -s -v
```
(test_optalg) C:\Users\psgu004\Documents\my_romcom\OPTALG>nosetests -s -v
test_mumps (tests.test_lin_solvers.TestOptSolvers) ... SKIP: no mumps
test_superlu (tests.test_lin_solvers.TestOptSolvers) ... ok
test_umfpack (tests.test_lin_solvers.TestOptSolvers) ... SKIP: no umfpack
test_augl_barrier (tests.test_opt_solvers.TestOptSolvers) ... ok
test_augl_properties_support (tests.test_opt_solvers.TestOptSolvers) ... ok
test_cbc (tests.test_opt_solvers.TestOptSolvers) ... SKIP: no cbc
test_cbc_cmd (tests.test_opt_solvers.TestOptSolvers) ... SKIP: no cbc command-line solver
test_cbc_cmd_lp_duals (tests.test_opt_solvers.TestOptSolvers) ... SKIP: no cbc cmd
test_cbc_cmd_properties_support (tests.test_opt_solvers.TestOptSolvers) ... SKIP: no cbc cmd
test_cbc_properties_support (tests.test_opt_solvers.TestOptSolvers) ... SKIP: no cbc
test_clp (tests.test_opt_solvers.TestOptSolvers) ... SKIP: no clp
test_clp_cmd (tests.test_opt_solvers.TestOptSolvers) ... SKIP: no clp command-line solver
test_clp_cmd_lp_duals (tests.test_opt_solvers.TestOptSolvers) ... SKIP: no clp cmd
test_clp_cmd_properties_support (tests.test_opt_solvers.TestOptSolvers) ... SKIP: no clp cmd
test_clp_properties_support (tests.test_opt_solvers.TestOptSolvers) ... SKIP: no clp
test_cplex_cmd (tests.test_opt_solvers.TestOptSolvers) ... SKIP: no cplex command-line solver
test_cplex_cmd_lp_duals (tests.test_opt_solvers.TestOptSolvers) ... SKIP: no cplex cmd
test_cplex_cmd_properties_support (tests.test_opt_solvers.TestOptSolvers) ... SKIP: no cplex cmd
test_inlp_properties_support (tests.test_opt_solvers.TestOptSolvers) ... ok
test_ipopt (tests.test_opt_solvers.TestOptSolvers) ... SKIP: no ipopt
test_ipopt_lp_duals (tests.test_opt_solvers.TestOptSolvers) ... SKIP: no ipopt
test_ipopt_properties_support (tests.test_opt_solvers.TestOptSolvers) ... SKIP: no ipopt
test_iqp_properties_support (tests.test_opt_solvers.TestOptSolvers) ... ok
test_iqp_random (tests.test_opt_solvers.TestOptSolvers) ... ok
test_nr_properties_support (tests.test_opt_solvers.TestOptSolvers) ... ok
test_solvers_on_LPs (tests.test_opt_solvers.TestOptSolvers) ... ok
test_solvers_on_QPs (tests.test_opt_solvers.TestOptSolvers) ... ok
test_lin_to_lp_file (tests.test_problems.TestProblems) ... ok
test_mixintlin_to_lp_file (tests.test_problems.TestProblems) ... ok

----------------------------------------------------------------------
Ran 29 tests in 6.566s

OK (SKIP=18)
```

**Comment by awig** [comment]
Thanks, @swaroopguggilam 
Are you and @fxz89 using virtual environments?
Does it happen with both Anaconda3 and vanilla Python3 installations? 

@TamerSobhy what is your setup?  Do you use Anconda3 and/or Python virtual environments? You don't have an EPRI laptop, correct?

**Comment by TamerSobhy** [comment]
@awig I don't use anaconda and I don't have an EPRI laptop. 
I am using python 3.7.4 with windows

**Comment by swaroopguggilam** [comment]
@awig 
I have tried in virtual environment as well as base python. (Vanilla Python Installation)
On Fans we tried on Base installation.
My python version on 3.7.4
I did not try Anaconda3.

**Comment by swaroopguggilam** [comment]
The actual error when solver is called:
'''
>>> from optalg.opt_solver import OptSolverAugL, OptSolverIpopt, OptSolverNR, OptSolverINLP
>>> solver = OptSolverIpopt()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\psgu004\Documents\my_romcom\OPTALG\optalg\opt_solver\ipopt.py", line 39, in __init__
    from ._ipopt import IpoptContext
  File "C:\Users\psgu004\Documents\my_romcom\OPTALG\optalg\opt_solver\_ipopt\__init__.py", line 9, in <module>
    from .cipopt import *
ImportError: DLL load failed: The specified module could not be found.
>>>
'''

**Comment by TamerSobhy** [comment]
It happened with me once before, I reinstalled the package and it worked.

**Comment by swaroopguggilam** [comment]
I see. I have tried many fresh new installations. Unfortunately it continues to give same error.

**Comment by swaroopguggilam** [comment]
@awig 
1 good news and 1 bad news.
Bad News: I tried again today for few hours to make IPOPT work. I tried debugging and tracing it down, but was not of much help. This is as far as I could get:
```
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\psgu004\Documents\my_romcom\romcom_materials\GAT\gat_virtualenv\test_gat\lib\site-packages\optalg-1.1.7rc1-py3.7-win-amd64.egg\optalg\opt_solver\_ipopt\__init__.py", line 9, in <module>
    from .cipopt import *
ImportError: DLL load failed: The specified module could not be found.
```
Good News: I thought why leave the option to try on Anaconda python 3 as I have already tried remaining things.
Guess what, it works. No Error. Nosetests Pass. It detects IPOPT and MUMPS.
```
(base) C:\Users\psgu004\Documents\my_romcom\OPTALG>nosetests -s -v
test_mumps (tests.test_lin_solvers.TestOptSolvers) ... ok
test_superlu (tests.test_lin_solvers.TestOptSolvers) ... ok
test_umfpack (tests.test_lin_solvers.TestOptSolvers) ... SKIP: no umfpack
test_augl_barrier (tests.test_opt_solvers.TestOptSolvers) ... ok
test_augl_properties_support (tests.test_opt_solvers.TestOptSolvers) ... ok
test_cbc (tests.test_opt_solvers.TestOptSolvers) ... SKIP: no cbc
test_cbc_cmd (tests.test_opt_solvers.TestOptSolvers) ... SKIP: no cbc command-line solver
test_cbc_cmd_lp_duals (tests.test_opt_solvers.TestOptSolvers) ... SKIP: no cbc cmd
test_cbc_cmd_properties_support (tests.test_opt_solvers.TestOptSolvers) ... SKIP: no cbc cmd
test_cbc_properties_support (tests.test_opt_solvers.TestOptSolvers) ... SKIP: no cbc
test_clp (tests.test_opt_solvers.TestOptSolvers) ... SKIP: no clp
test_clp_cmd (tests.test_opt_solvers.TestOptSolvers) ... SKIP: no clp command-line solver
test_clp_cmd_lp_duals (tests.test_opt_solvers.TestOptSolvers) ... SKIP: no clp cmd
test_clp_cmd_properties_support (tests.test_opt_solvers.TestOptSolvers) ... SKIP: no clp cmd
test_clp_properties_support (tests.test_opt_solvers.TestOptSolvers) ... SKIP: no clp
test_cplex_cmd (tests.test_opt_solvers.TestOptSolvers) ... SKIP: no cplex command-line solver
test_cplex_cmd_lp_duals (tests.test_opt_solvers.TestOptSolvers) ... SKIP: no cplex cmd
test_cplex_cmd_properties_support (tests.test_opt_solvers.TestOptSolvers) ... SKIP: no cplex cmd
test_inlp_properties_support (tests.test_opt_solvers.TestOptSolvers) ... ok
test_ipopt (tests.test_opt_solvers.TestOptSolvers) ... ok
test_ipopt_lp_duals (tests.test_opt_solvers.TestOptSolvers) ... ok
test_ipopt_properties_support (tests.test_opt_solvers.TestOptSolvers) ... ok
test_iqp_properties_support (tests.test_opt_solvers.TestOptSolvers) ... ok
test_iqp_random (tests.test_opt_solvers.TestOptSolvers) ... ok
test_nr_properties_support (tests.test_opt_solvers.TestOptSolvers) ... ok
test_solvers_on_LPs (tests.test_opt_solvers.TestOptSolvers) ... ok
test_solvers_on_QPs (tests.test_opt_solvers.TestOptSolvers) ... ok
test_lin_to_lp_file (tests.test_problems.TestProblems) ... ok
test_mixintlin_to_lp_file (tests.test_problems.TestProblems) ... ok

----------------------------------------------------------------------
Ran 29 tests in 4.789s

OK (SKIP=14)
```
Although not yet sure, what to conclude from this and why is it not working on the Vanilla python 3 installation. But at least now, I have some option to work on.

@fxz89  Can you please try Anaconda 3 approach on your laptop as well?

**Comment by fxz89** [comment]
Hi Swaroop, I just tried nosetests on OPTALG in Anaconda 3, the issue of no mumps/ipopt is gone, I got the same result as you have in good news.

**Comment by awig** [comment]
Thanks @fxz89 @swaroopguggilam 

Swaroop verified Anaconda3 is built for 64bit  MSVC
```
Python 3.7.6 (default, Jan  8 2020, 20:23:39) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32
```

Vanilla Python3 is the same, so it doesn't seem like an issue with the DLLs.

Don't have any particular ideas now. Perhaps try reinstalling vanilla Python3? Anyway, we can revisit this later, it has taken enough time.

**Comment by swaroopguggilam** [comment]
Possible places to check (when attempting to fix in the future):
https://github.com/matthias-k/cyipopt#example-installation-on-ubuntu-1804-with-custom-compiled-ipopt
https://github.com/matthias-k/cyipopt/issues/21
https://github.com/matthias-k/cyipopt/pull/49
